Unit GUIRegionsList;
interface

uses
  Windows, Messages, SysUtils, Variants, Classes, Graphics, Controls, Forms,
  Dialogs, StdCtrls, AgeDxFormDataD, Grids, AgeDxStringGridD, AgeDxImageD,
  AgeDxLabelD, AgeDxButtonD, ExtCtrls, AgeDxGripBarD, AgeDxScrollBarD;

type
  TMainForm = class(TForm)
   AgeGripBar: TAgeGripBarD;
   btnClose: TAgeButtonD;
   AgeDxFormDataD: TAgeDxFormDataD;
    lbTitle: TAgeLabelD;
    AgeGripBar: TAgeGripBarD;
    btnClose: TAgeButtonD;

    imgFacTagBack1: TAgeImageD;
    imgFacTagBack2: TAgeImageD;
    imgFacTagBack3: TAgeImageD;
    imgFacTagBack4: TAgeImageD;
    imgFacTagBack5: TAgeImageD;
    imgFacTagBack6: TAgeImageD;
    imgFacTagBack7: TAgeImageD;
    imgFacTagBack8: TAgeImageD;
    imgFacTagBack9: TAgeImageD;
    imgFacTagBack10: TAgeImageD;
    imgFacTagBack11: TAgeImageD;
    imgFacTagBack12: TAgeImageD;
    imgFacTagBack13: TAgeImageD;
    imgFacTagBack14: TAgeImageD;
    imgFacTagBack15: TAgeImageD;
    imgFacTagBack16: TAgeImageD;
    imgFacTag1: TAgeImageD;
    imgFacTag2: TAgeImageD;
    imgFacTag3: TAgeImageD;
    imgFacTag4: TAgeImageD;
    imgFacTag5: TAgeImageD;
    imgFacTag6: TAgeImageD;
    imgFacTag7: TAgeImageD;
    imgFacTag8: TAgeImageD;
    imgFacTag9: TAgeImageD;
    imgFacTag10: TAgeImageD;
    imgFacTag11: TAgeImageD;
    imgFacTag12: TAgeImageD;
    imgFacTag13: TAgeImageD;
    imgFacTag14: TAgeImageD;
    imgFacTag15: TAgeImageD;
    imgFacTag16: TAgeImageD;
    lbRegionName1: TAgeLabelD;
    lbRegionName2: TAgeLabelD;
    lbRegionName3: TAgeLabelD;
    lbRegionName4: TAgeLabelD;
    lbRegionName5: TAgeLabelD;
    lbRegionName6: TAgeLabelD;
    lbRegionName7: TAgeLabelD;
    lbRegionName8: TAgeLabelD;
    lbRegionName9: TAgeLabelD;
    lbRegionName10: TAgeLabelD;
    lbRegionName11: TAgeLabelD;
    lbRegionName12: TAgeLabelD;
    lbRegionName13: TAgeLabelD;
    lbRegionName14: TAgeLabelD;
    lbRegionName15: TAgeLabelD;
    lbRegionName16: TAgeLabelD;
    lbTransportLevel1: TAgeLabelD;
    lbTransportLevel2: TAgeLabelD;
    lbTransportLevel3: TAgeLabelD;
    lbTransportLevel4: TAgeLabelD;
    lbTransportLevel5: TAgeLabelD;
    lbTransportLevel6: TAgeLabelD;
    lbTransportLevel7: TAgeLabelD;
    lbTransportLevel8: TAgeLabelD;
    lbTransportLevel9: TAgeLabelD;
    lbTransportLevel10: TAgeLabelD;
    lbTransportLevel11: TAgeLabelD;
    lbTransportLevel12: TAgeLabelD;
    lbTransportLevel13: TAgeLabelD;
    lbTransportLevel14: TAgeLabelD;
    lbTransportLevel15: TAgeLabelD;
    lbTransportLevel16: TAgeLabelD;
    lbTerrainType1: TAgeLabelD;
    lbTerrainType2: TAgeLabelD;
    lbTerrainType3: TAgeLabelD;
    lbTerrainType4: TAgeLabelD;
    lbTerrainType5: TAgeLabelD;
    lbTerrainType6: TAgeLabelD;
    lbTerrainType7: TAgeLabelD;
    lbTerrainType8: TAgeLabelD;
    lbTerrainType9: TAgeLabelD;
    lbTerrainType10: TAgeLabelD;
    lbTerrainType11: TAgeLabelD;
    lbTerrainType12: TAgeLabelD;
    lbTerrainType13: TAgeLabelD;
    lbTerrainType14: TAgeLabelD;
    lbTerrainType15: TAgeLabelD;
    lbTerrainType16: TAgeLabelD;
    imgWeatherType1: TAgeImageD;
    imgWeatherType2: TAgeImageD;
    imgWeatherType3: TAgeImageD;
    imgWeatherType4: TAgeImageD;
    imgWeatherType5: TAgeImageD;
    imgWeatherType6: TAgeImageD;
    imgWeatherType7: TAgeImageD;
    imgWeatherType8: TAgeImageD;
    imgWeatherType9: TAgeImageD;
    imgWeatherType10: TAgeImageD;
    imgWeatherType11: TAgeImageD;
    imgWeatherType12: TAgeImageD;
    imgWeatherType13: TAgeImageD;
    imgWeatherType14: TAgeImageD;
    imgWeatherType15: TAgeImageD;
    imgWeatherType16: TAgeImageD;
    lbMilControl1: TAgeLabelD;
    lbMilControl2: TAgeLabelD;
    lbMilControl3: TAgeLabelD;
    lbMilControl4: TAgeLabelD;
    lbMilControl5: TAgeLabelD;
    lbMilControl6: TAgeLabelD;
    lbMilControl7: TAgeLabelD;
    lbMilControl8: TAgeLabelD;
    lbMilControl9: TAgeLabelD;
    lbMilControl10: TAgeLabelD;
    lbMilControl11: TAgeLabelD;
    lbMilControl12: TAgeLabelD;
    lbMilControl13: TAgeLabelD;
    lbMilControl14: TAgeLabelD;
    lbMilControl15: TAgeLabelD;
    lbMilControl16: TAgeLabelD;
    lbLoyalty1: TAgeLabelD;
    lbLoyalty2: TAgeLabelD;
    lbLoyalty3: TAgeLabelD;
    lbLoyalty4: TAgeLabelD;
    lbLoyalty5: TAgeLabelD;
    lbLoyalty6: TAgeLabelD;
    lbLoyalty7: TAgeLabelD;
    lbLoyalty8: TAgeLabelD;
    lbLoyalty9: TAgeLabelD;
    lbLoyalty10: TAgeLabelD;
    lbLoyalty11: TAgeLabelD;
    lbLoyalty12: TAgeLabelD;
    lbLoyalty13: TAgeLabelD;
    lbLoyalty14: TAgeLabelD;
    lbLoyalty15: TAgeLabelD;
    lbLoyalty16: TAgeLabelD;
    lbMoney1: TAgeLabelD;
    lbMoney2: TAgeLabelD;
    lbMoney3: TAgeLabelD;
    lbMoney4: TAgeLabelD;
    lbMoney5: TAgeLabelD;
    lbMoney6: TAgeLabelD;
    lbMoney7: TAgeLabelD;
    lbMoney8: TAgeLabelD;
    lbMoney9: TAgeLabelD;
    lbMoney10: TAgeLabelD;
    lbMoney11: TAgeLabelD;
    lbMoney12: TAgeLabelD;
    lbMoney13: TAgeLabelD;
    lbMoney14: TAgeLabelD;
    lbMoney15: TAgeLabelD;
    lbMoney16: TAgeLabelD;
    lbWSU1: TAgeLabelD;
    lbWSU2: TAgeLabelD;
    lbWSU3: TAgeLabelD;
    lbWSU4: TAgeLabelD;
    lbWSU5: TAgeLabelD;
    lbWSU6: TAgeLabelD;
    lbWSU7: TAgeLabelD;
    lbWSU8: TAgeLabelD;
    lbWSU9: TAgeLabelD;
    lbWSU10: TAgeLabelD;
    lbWSU11: TAgeLabelD;
    lbWSU12: TAgeLabelD;
    lbWSU13: TAgeLabelD;
    lbWSU14: TAgeLabelD;
    lbWSU15: TAgeLabelD;
    lbWSU16: TAgeLabelD;
    lbConscript1: TAgeLabelD;
    lbConscript2: TAgeLabelD;
    lbConscript3: TAgeLabelD;
    lbConscript4: TAgeLabelD;
    lbConscript5: TAgeLabelD;
    lbConscript6: TAgeLabelD;
    lbConscript7: TAgeLabelD;
    lbConscript8: TAgeLabelD;
    lbConscript9: TAgeLabelD;
    lbConscript10: TAgeLabelD;
    lbConscript11: TAgeLabelD;
    lbConscript12: TAgeLabelD;
    lbConscript13: TAgeLabelD;
    lbConscript14: TAgeLabelD;
    lbConscript15: TAgeLabelD;
    lbConscript16: TAgeLabelD;
    lbCityLevel1: TAgeLabelD;
    lbCityLevel2: TAgeLabelD;
    lbCityLevel3: TAgeLabelD;
    lbCityLevel4: TAgeLabelD;
    lbCityLevel5: TAgeLabelD;
    lbCityLevel6: TAgeLabelD;
    lbCityLevel7: TAgeLabelD;
    lbCityLevel8: TAgeLabelD;
    lbCityLevel9: TAgeLabelD;
    lbCityLevel10: TAgeLabelD;
    lbCityLevel11: TAgeLabelD;
    lbCityLevel12: TAgeLabelD;
    lbCityLevel13: TAgeLabelD;
    lbCityLevel14: TAgeLabelD;
    lbCityLevel15: TAgeLabelD;
    lbCityLevel16: TAgeLabelD;
    lbHarborLevel1: TAgeLabelD;
    lbHarborLevel2: TAgeLabelD;
    lbHarborLevel3: TAgeLabelD;
    lbHarborLevel4: TAgeLabelD;
    lbHarborLevel5: TAgeLabelD;
    lbHarborLevel6: TAgeLabelD;
    lbHarborLevel7: TAgeLabelD;
    lbHarborLevel8: TAgeLabelD;
    lbHarborLevel9: TAgeLabelD;
    lbHarborLevel10: TAgeLabelD;
    lbHarborLevel11: TAgeLabelD;
    lbHarborLevel12: TAgeLabelD;
    lbHarborLevel13: TAgeLabelD;
    lbHarborLevel14: TAgeLabelD;
    lbHarborLevel15: TAgeLabelD;
    lbHarborLevel16: TAgeLabelD;
    lbDepotLevel1: TAgeLabelD;
    lbDepotLevel2: TAgeLabelD;
    lbDepotLevel3: TAgeLabelD;
    lbDepotLevel4: TAgeLabelD;
    lbDepotLevel5: TAgeLabelD;
    lbDepotLevel6: TAgeLabelD;
    lbDepotLevel7: TAgeLabelD;
    lbDepotLevel8: TAgeLabelD;
    lbDepotLevel9: TAgeLabelD;
    lbDepotLevel10: TAgeLabelD;
    lbDepotLevel11: TAgeLabelD;
    lbDepotLevel12: TAgeLabelD;
    lbDepotLevel13: TAgeLabelD;
    lbDepotLevel14: TAgeLabelD;
    lbDepotLevel15: TAgeLabelD;
    lbDepotLevel16: TAgeLabelD;
    lbPowerOwn1: TAgeLabelD;
    lbPowerOwn2: TAgeLabelD;
    lbPowerOwn3: TAgeLabelD;
    lbPowerOwn4: TAgeLabelD;
    lbPowerOwn5: TAgeLabelD;
    lbPowerOwn6: TAgeLabelD;
    lbPowerOwn7: TAgeLabelD;
    lbPowerOwn8: TAgeLabelD;
    lbPowerOwn9: TAgeLabelD;
    lbPowerOwn10: TAgeLabelD;
    lbPowerOwn11: TAgeLabelD;
    lbPowerOwn12: TAgeLabelD;
    lbPowerOwn13: TAgeLabelD;
    lbPowerOwn14: TAgeLabelD;
    lbPowerOwn15: TAgeLabelD;
    lbPowerOwn16: TAgeLabelD;
    lbPowerEnm1: TAgeLabelD;
    lbPowerEnm2: TAgeLabelD;
    lbPowerEnm3: TAgeLabelD;
    lbPowerEnm4: TAgeLabelD;
    lbPowerEnm5: TAgeLabelD;
    lbPowerEnm6: TAgeLabelD;
    lbPowerEnm7: TAgeLabelD;
    lbPowerEnm8: TAgeLabelD;
    lbPowerEnm9: TAgeLabelD;
    lbPowerEnm10: TAgeLabelD;
    lbPowerEnm11: TAgeLabelD;
    lbPowerEnm12: TAgeLabelD;
    lbPowerEnm13: TAgeLabelD;
    lbPowerEnm14: TAgeLabelD;
    lbPowerEnm15: TAgeLabelD;
    lbPowerEnm16: TAgeLabelD;
    imgLock1: TAgeImageD;
    imgLock2: TAgeImageD;
    imgLock3: TAgeImageD;
    imgLock4: TAgeImageD;
    imgLock5: TAgeImageD;
    imgLock6: TAgeImageD;
    imgLock7: TAgeImageD;
    imgLock8: TAgeImageD;
    imgLock9: TAgeImageD;
    imgLock10: TAgeImageD;
    imgLock11: TAgeImageD;
    imgLock12: TAgeImageD;
    imgLock13: TAgeImageD;
    imgLock14: TAgeImageD;
    imgLock15: TAgeImageD;
    imgLock16: TAgeImageD;
    lbVP1: TAgeLabelD;
    lbVP2: TAgeLabelD;
    lbVP3: TAgeLabelD;
    lbVP4: TAgeLabelD;
    lbVP5: TAgeLabelD;
    lbVP6: TAgeLabelD;
    lbVP7: TAgeLabelD;
    lbVP8: TAgeLabelD;
    lbVP9: TAgeLabelD;
    lbVP10: TAgeLabelD;
    lbVP11: TAgeLabelD;
    lbVP12: TAgeLabelD;
    lbVP13: TAgeLabelD;
    lbVP14: TAgeLabelD;
    lbVP15: TAgeLabelD;
    lbVP16: TAgeLabelD;
    AgeScrollBarD1: TAgeScrollBarD;
    btnHeadTag: TAgeButtonD;
    btnHeadRegionName: TAgeButtonD;
    btnHeadTransportLvl: TAgeButtonD;
    btnHeadTerrain: TAgeButtonD;
    btnHeadMilControl: TAgeButtonD;
    btnHeadLoyalty: TAgeButtonD;
    btnHeadMoney: TAgeButtonD;
    btnHeadWSU: TAgeButtonD;
    btnHeadConscript: TAgeButtonD;
    btnHeadCityLevel: TAgeButtonD;
    btnHeadHarborLevel: TAgeButtonD;
    btnHeadDepotLevel: TAgeButtonD;
    btnHeadOwnPower: TAgeButtonD;
    btnHeadEnmPower: TAgeButtonD;
    btnHeadVP: TAgeButtonD;
    lbTableTitle: TAgeLabelD;
    btnFilterLoyalty: TAgeButtonD;
    btnFilterMilControl: TAgeButtonD;
    btnFilterRailroad: TAgeButtonD;
    btnFilterHighSupply: TAgeButtonD;
    btnFilterOwnCbtPower: TAgeButtonD;
    btnFilterEnmCbtPower: TAgeButtonD;
    btnFilterProdStructures: TAgeButtonD;
    btnFilterDepot: TAgeButtonD;
    btnFilterHarbor: TAgeButtonD;
    btnFlag1: TAgeButtonD;
    btnFlag2: TAgeButtonD;
    btnFlag3: TAgeButtonD;
    btnFlag4: TAgeButtonD;
    btnFlag5: TAgeButtonD;
    btnFlag6: TAgeButtonD;
    btnFlag7: TAgeButtonD;
    btnFlag8: TAgeButtonD;
    btnFlag9: TAgeButtonD;
    btnFlag10: TAgeButtonD;
    btnFlag11: TAgeButtonD;
    btnFlag12: TAgeButtonD;
    imgLedgerTab8: TAgeButtonD;
    imgLedgerTab9: TAgeButtonD;
    imgLedgerTab7: TAgeButtonD;
    imgLedgerTab6: TAgeButtonD;
    imgLedgerTab5: TAgeButtonD;
    imgLedgerTab4: TAgeButtonD;
    imgLedgerTab3: TAgeButtonD;
    imgLedgerTab2: TAgeButtonD;
    imgLedgerTab1: TAgeButtonD;
    imgLedgerTab0: TAgeButtonD;
	
    procedure FormCreate(Sender: TObject);
  private
    { Déclarations privées }
  public
    { Déclarations publiques }
  end;

var
  MainForm: TMainForm;

implementation

{$R *.dfm}

procedure TMainForm.FormCreate(Sender: TObject);
begin
object AgeImageD13: TAgeImageD
  Left = 835
  Top = 112
  Width = 50
  Height = 41
  Caption = 'Trench'
  TabOrder = 16
  DataSetIdx = 0
end

end;

end.
