SetAdvRevolt = GRN|60|60|120|10|101|NULL|NULL
SetAdvRevoltFP = GRN|$uni_GRN_Pes|100|$uni_GRN_Inf_Par|50|$uni_GRN_Cav_Par|60|$uni_BSH_Rgt|4|$uni_BSH_Cav|1

SetAdvRevolt = WHI|60|60|120|10|101|NULL|NULL
SetAdvRevoltFP = WHI|$uni_WHI_Inf_Par|16|$uni_WHI_Cav_Par|4

SetAdvRevolt = WH5|60|60|120|10|101|NULL|NULL
SetAdvRevoltFP = WH5|$uni_WH3_Inf_Par|8|$uni_WH3_Cav_Par|2|$uni_WH2_Inf_Par|8|$uni_WH2_Cav_Par|2

SetAdvRevolt = WH7|60|60|120|10|101|NULL|NULL
SetAdvRevoltFP = WH7|$uni_WH3_Inf_Par|8|$uni_WH3_Cav_Par|2|$uni_WH2_Inf_Par|8|$uni_WH2_Cav_Par|2

SetAdvRevolt = RED|60|60|120|10|101|NULL|NULL
SetAdvRevoltFP = RED|$uni_RED_Inf_Par|32|$uni_RED_Cav_Par|8

SetAdvRevolt = ANA|60|60|120|10|101|NULL|NULL
SetAdvRevoltFP = ANA|$uni_ANA_SibInf|20|$uni_ANA_UkrInf|20|$uni_ANA_SibCav|10|$uni_ANA_UkrCav|10

SetAdvRevolt = UKR|60|60|120|10|101|NULL|NULL
SetAdvRevoltFP = UKR|$uni_UKR_Inf_Par|8|$uni_UKR_Cav_Par|2

SetAdvRevolt = EST|60|60|120|10|101|NULL|NULL
SetAdvRevoltFP = EST|$uni_EST_Inf_Par|8

SetAdvRevolt = LAT|60|60|120|10|101|NULL|NULL
SetAdvRevoltFP = LAT|$uni_LAT_Inf_Par|8

SetAdvRevolt = LIT|60|60|120|10|101|NULL|NULL
SetAdvRevoltFP = LIT|$uni_LIT_Inf_Par|8

SetAdvRevolt = ARM|60|60|120|10|101|NULL|NULL
SetAdvRevoltFP = ARM|$uni_ARM_Inf_Par|8|$uni_ARM_Cav_Par|2

SetAdvRevolt = AZR|60|60|120|10|101|NULL|NULL
SetAdvRevoltFP = AZR|$uni_AZR_Inf_Par|8|$uni_AZR_Cav_Par|2

SetAdvRevolt = GEO|60|60|120|10|101|NULL|NULL
SetAdvRevoltFP = GEO|$uni_GEO_Inf_Par|8|$uni_GEO_Cav_Par|2

SetAdvRevolt = FIN|60|60|120|10|101|NULL|NULL
SetAdvRevoltFP = FIN|$uni_FIN_Inf_Par|16

SetAdvRevolt = ROM|60|60|120|10|101|NULL|NULL
SetAdvRevoltFP = ROM|$uni_ROM_Inf_Par|8

SetAdvRevolt = BAS|60|60|120|10|101|NULL|NULL
SetAdvRevoltFP = BAS|$uni_KAZ_Inf_Par|10|$uni_KAZ_Cav_Par|10

SetAdvRevolt = POL|60|60|120|10|101|NULL|NULL
SetAdvRevoltFP = POL|$uni_POL_Inf_Par|40