SelectFaction = $RED
SelectRegion = $Krasnaya Gorka
  CreateGroup
  Posture = $Defensive
  SetKind = $Land
  Entranch = 8
  InCS = 1
  FixType = 999
  SetName = Krasnaya Gorka Fort
  Apply
  CreateUnit
  SetType = $uni_RED_Gar
  FlavorName = Comrade Solodukin
  SetName = 19th Fusiliers Div.
  Apply
  CreateUnit
  SetType = $uni_RED_Bty
  SetName = Krasnaya Gorka Bty
  Apply
  CreateUnit
  SetType = $uni_RED_Coa
  SetName = Krasnaya Gorka Costal Bty
  Apply
  CreateUnit
  SetType = $uni_RED_Sup1
  SetName = Krasnaya Gorka Supply
  Apply

SelectFaction = $RED
SelectRegion = $Petrograd
  CreateGroup
  Posture = $Defensive
  SetKind = $Land
  Entranch = 4
  InCS = 1
  FixType = 999
  SetName = Petrograd Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Gar
  SetName = Petrograd Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Gar
  SetName = Petrograd Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Gar
  SetName = Petrograd Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Gar
  SetName = Petrograd Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Bty
  SetName = Petrograd Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Bty
  SetName = Petrograd Garrison
  Apply

SelectFaction = $RED
SelectRegion = $Moscow
  CreateGroup
  Posture = $Defensive
  SetKind = $Land
  Entranch = 4
  InCS = 1
  FixType = 999
  SetName = Moscow Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Gar
  SetName = Moscow Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Gar
  SetName = Moscow Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Gar
  SetName = Moscow Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Gar
  SetName = Moscow Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Bty
  SetName = Moscow Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Bty
  SetName = Moscow Garrison
  Apply

SelectFaction = $RED
SelectRegion = $Kronstadt
  CreateGroup
  Posture = $Defensive
  SetKind = $Land
  Entranch = 6
  InCS = 1
  FixType = 999
  SetName = Kronstadt Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Gar
  SetName = Kronstadt Base Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Sup2
  SetName = Kronstadt Stores
  Apply
  SetHealth = 10
  SetCohesion = 10

SelectFaction = $RED
SelectRegion = $Ekaterinodar
  CreateGroup
  Posture = $Defensive
  SetKind = $Land
  Entranch = 0
  InCS = 0
  FixType = 999
  SetName = Ekaterinodar Garrison
  Apply
  CreateUnit
    SetType = $uni_RED_Mil1
    SetName = 1st Infantry Rgt
  Apply
  CreateUnit
    SetType = $uni_RED_Mil1
    SetName = 2nd Infantry Rgt
  Apply
  CreateUnit
    SetType = $uni_RED_Mil1
    SetName = 3rd Infantry Rgt
  Apply
  CreateUnit
    SetType = $uni_RED_Mil1
    SetName = 4th Infantry Rgt
  Apply
  CreateUnit
    SetType = $uni_RED_ConCav1
    SetName = 1st Cavalry Rgt
  Apply
  CreateUnit
    SetType = $uni_RED_MG2
    SetName = Machine Guns
  Apply
  CreateUnit
    SetType = $uni_RED_Art1
    SetName = Artillery Bty
  Apply

SelectFaction = $RED
SelectRegion = $Stavropol
  CreateGroup
  Posture = $Defensive
  SetKind = $Land
  Entranch = 0
  InCS = 0
  FixType = 999
  SetName = Stavropol Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Mil1
  SetName = 1st Stavropol Red Gds
  Apply
  CreateUnit
  SetType = $uni_RED_Mil1
  SetName = 2nd Stavropol Red Gds
  Apply

SelectFaction = $WH7
SelectRegion = $Harbin
  CreateGroup
  Posture = $Defensive
  SetKind = $Land
  Entranch = 0
  InCS = 0
  FixType = 999
  SetName = Harbin Garrison
  Apply
  CreateUnit
  SetType = $uni_CHI_Inf
  SetName = Harbin Rgt
  Apply