
SelectFaction = RED
  AddGarrison = -1;$sfmCity;$uni_RED_Mil1;100;x;x;x;x

SelectFaction = WHI
  AddGarrison = -1;$sfmCity;$uni_WHI_Mil1;100;x;x;x;x

SelectFaction = WH5
  AddGarrison = -1;$sfmCity;$uni_WH3_Mil1;100;x;x;x;x

SelectFaction = WH7
  AddGarrison = -1;$sfmCity;$uni_WH3_Mil1;100;x;x;x;x

SelectFaction = UKR
  AddGarrison = $Theater_Ukraine;$sfmCity;$uni_UKR_Mil1;100;x;x;x;x

SelectFaction = GRN
  AddGarrison = -1;$sfmCity;$uni_GRN_Pes;100;x;x;x;x

SelectFaction = ANA
  AddGarrison = $Recruit_ANA_Siberian;$sfmCity;$uni_ANA_SibInf;100;x;x;x;x
  AddGarrison = $Recruit_ANA_Ukrainian;$sfmCity;$uni_ANA_UkrInf;100;x;x;x;x

SelectFaction = BAS
  AddGarrison = $Theater_Central_Asia;$sfmCity;$uni_KAZ_Mil;100;x;x;x;x

SelectFaction = FIN
  AddGarrison = $Theater_Finland;$sfmCity;$uni_FIN_Mil;100;x;x;x;x

SelectFaction = ROM
  AddGarrison = $Theater_Romania;$sfmCity;$uni_ROM_Mil;100;x;x;x;x

SelectFaction = LIT
  AddGarrison = $Theater_Baltics;$sfmCity;$uni_LIT_Mil;100;x;x;x;x

SelectFaction = LAT
  AddGarrison = $Theater_Baltics;$sfmCity;$uni_LAT_Mil;100;x;x;x;x

SelectFaction = EST
  AddGarrison = $Theater_Baltics;$sfmCity;$uni_EST_Mil;100;x;x;x;x

SelectFaction = POL
  AddGarrison = $Theater_Poland;$sfmCity;$uni_POL_Mil;100;x;x;x;x

SelectFaction = GEO
  AddGarrison = $Theater_Transcaucasia;$sfmCity;$uni_GEO_Mil;100;x;x;x;x

SelectFaction = ARM
  AddGarrison = $Theater_Transcaucasia;$sfmCity;$uni_ARM_Mil;100;x;x;x;x

SelectFaction = AZR
  AddGarrison = $Theater_Transcaucasia;$sfmCity;$uni_AZR_Mil;100;x;x;x;x

SelectFaction = JAP
  AddGarrison = $Theater_Eastern;$sfmCity;$uni_ZAB_Inf;100;x;x;x;x
