  NULL = NULL

SelectFaction = $RED
SelectRegion = $Kazan

SelectRegion = $Kazan

SelectFaction = $RED
SelectRegion = $Kazan
  CreateGroup
  Posture = $Defensive
  SetKind = $Nav
  Entranch = 0
  SetName = Kazan Transports
  Apply
  CreateUnit
  SetType = $uni_RED_RT1
  SUFlavorName = Opyt|Sobol|Gornostai|Pishtchal
  SetName = Kazan Transport Sqd
  Apply

SelectRegion = $Nizhniy Novgorod

SelectFaction = $RED
SelectRegion = $Nizhniy Novgorod
  CreateGroup
  Posture = $Defensive
  SetKind = $Nav
  Entranch = 0
  SetName = Nizhniy Novgorod Transports
  Apply
  CreateUnit
  SetType = $uni_RED_RT1
  SUFlavorName = Syekira|Ersh|Nerpa| Burun|
  SetName = Nizhniy Novgorod Transport Sqd
  Apply

SelectRegion = $Samara

SelectFaction = $RED
SelectRegion = $Samara
  CreateGroup
  Posture = $Defensive
  SetKind = $Nav
  Entranch = 0
  SetName = Samara Transports
  Apply
  CreateUnit
  SetType = $uni_RED_RT1
  SUFlavorName = Tutcha|Burya|Groza|Dojd|
  SetName = Samara Transport Sqd
  Apply

SelectRegion = $Tzaritsyn

SelectFaction = $RED
SelectRegion = $Tzaritsyn
  CreateGroup
  Posture = $Defensive
  SetKind = $Nav
  Entranch = 0
  SetName = Tzaritsyn Transports
  Apply
  CreateUnit
  SetType = $uni_RED_RT1
  SUFlavorName = Vikhr|Suyez|Grad|Amur|
  SetName = Tzaritsyn Transport Sqd
  Apply

SelectRegion = $Astrakhan

SelectFaction = $RED
SelectRegion = $Astrakhan
  CreateGroup
  Posture = $Defensive
  SetKind = $Nav
  Entranch = 0
  SetName = Astrakhan Transports
  Apply
  CreateUnit
  SetType = $uni_RED_RT1
  SUFlavorName = Yensei|Leitenant Ilin|Kapitan Saken|Kazaeski|
  SetName = Astrakhan Transport Sqd
  Apply

SelectRegion = $Yaroslavl

SelectFaction = $RED
SelectRegion = $Yaroslavl
  CreateGroup
  Posture = $Defensive
  SetKind = $Nav
  Entranch = 0
  SetName = Yaroslav Transports
  Apply
  CreateUnit
  SetType = $uni_RED_RT1
  SUFlavorName = Voevoda|Posadnik|Vsadnik|Gaidamak|
  SetName = Yaroslav Transport Sqd
  Apply

SelectRegion = $Kotlas

SelectFaction = $RED
SelectRegion = $Kotlas
  CreateGroup
  Posture = $Defensive
  SetKind = $Nav
  Entranch = 0
  SetName = Kotlas Transports
  Apply
  CreateUnit
  SetType = $uni_RED_RT1
  NumCreate = 2
  SUFlavorName = Grinden|Abrek
  SetName = Kotlas Transport Sqd
  Apply

SelectRegion = $Voronezh

SelectFaction = $RED
SelectRegion = $Voronezh
  CreateGroup
  Posture = $Defensive
  SetKind = $Nav
  Entranch = 0
  SetName = Voronezh Transports
  Apply
  CreateUnit
  SetType = $uni_RED_RT1
  SUFlavorName = Chesma|Georgi Pobiedonosets|Sinop|Dvienadstat Aposotolev
  SetName = Voronezh Transport Sqd
  Apply

SelectRegion = $Perm

SelectFaction = $RED
SelectRegion = $Perm
  CreateGroup
  Posture = $Defensive
  SetKind = $Nav
  Entranch = 0
  SetName = Perm Transports
  Apply
  CreateUnit
  SetType = $uni_RED_RT1
  SUFlavorName = Gangut|Navarin|Tri Svititelia|Sissoli Veliki
  SetName = Perm Transport Sqd
  Apply

SelectRegion = $Bobruisk

SelectFaction = $RED
SelectRegion = $Bobruisk
  CreateGroup
  Posture = $Defensive
  SetKind = $Nav
  Entranch = 0
  SetName = Bobruisk Transports
  Apply
  CreateUnit
  SetType = $uni_RED_RT1
  SUFlavorName = Ushakov|Senavin|Apraksin|Petropavlovsk
  SetName = Bobruisk Transport Sqd
  Apply

SelectRegion = $Kharkov

SelectFaction = $RED
SelectRegion = $Kharkov
  CreateGroup
  Posture = $Defensive
  SetKind = $Nav
  Entranch = 0
  SetName = Kharkov Transports
  Apply
  CreateUnit
  SetType = $uni_RED_RT1
  SUFlavorName = Poltava|Sevastopol|Rostislav|Peresviet|
  SetName = Kharkov Transport Sqd
  Apply

SelectRegion = $Petrograd

SelectFaction = $RED
SelectRegion = $Petrograd
  CreateGroup
  Posture = $Defensive
  SetKind = $Nav
  Entranch = 0
  SetName = Ladoga Transports
  Apply
  CreateUnit
  SetType = $uni_RED_RT1
  SUFlavorName = Osliabia|Pantelimon|Retvisan|Borodino|
  SetName = Ladoga Transport Sqd
  Apply

SelectRegion = $Saratov

SelectFaction = $RED
SelectRegion = $Saratov
  CreateGroup
  Posture = $Defensive
  SetKind = $Nav
  Entranch = 0
  SetName = Saratov Ferry
  Apply
  CreateUnit
  SetType = $uni_RED_RT2
  SUFlavorName = Saratov Barge #1|Saratov Barge #2t|Saratov Barge #3|Saratov Barge #4
  SetName = Saratov Ferry
  Apply

SelectRegion = $Syzran

SelectFaction = $RED
SelectRegion = $Syzran
  CreateGroup
  Posture = $Defensive
  SetKind = $Nav
  Entranch = 0
  SetName = Syzran Ferry
  Apply
  CreateUnit
  SetType = $uni_RED_RT2
  SUFlavorName = Syzran Barge #1|Syzran Barge #2t|Syzran Barge #3|Syzran Barge #4
  SetName = Syzran Ferry
  Apply

SelectRegion = $Cheboksary

SelectFaction = $RED
SelectRegion = $Cheboksary
  CreateGroup
  Posture = $Defensive
  SetKind = $Nav
  Entranch = 0
  SetName = Cheboksary Ferry
  Apply
  CreateUnit
  SetType = $uni_RED_RT2
  SUFlavorName = Cheboksary Barge #1|Cheboksary Barge #2t|Cheboksary Barge #3|Cheboksary Barge #4
  SetName = Cheboksary Ferry
  Apply

SelectRegion = $Kostroma

SelectFaction = $RED
SelectRegion = $Kostroma
  CreateGroup
  Posture = $Defensive
  SetKind = $Nav
  Entranch = 0
  SetName = Kostroma Ferry
  Apply
  CreateUnit
  SetType = $uni_RED_RT2
  SUFlavorName = Kostroma Barge #1|Kostroma Barge #2t|Kostroma Barge #3|Kostroma Barge #4
  SetName = Kostroma Ferry
  Apply

SelectRegion = $Rybinsk

SelectFaction = $RED
SelectRegion = $Rybinsk
  CreateGroup
  Posture = $Defensive
  SetKind = $Nav
  Entranch = 0
  SetName = Rybinsk Ferry
  Apply
  CreateUnit
  SetType = $uni_RED_RT2
  SUFlavorName = Rybinsk Barge #1|Rybinsk Barge #2t|Rybinsk Barge #3|Rybinsk Barge #4
  SetName = Rybinsk Ferry
  Apply

SelectRegion = $Novgorod

SelectFaction = $RED
SelectRegion = $Novgorod
  CreateGroup
  Posture = $Defensive
  SetKind = $Nav
  Entranch = 0
  SetName = Novgorod Ferry
  Apply
  CreateUnit
  SetType = $uni_RED_RT2
  SUFlavorName = Novgorod Barge #1|Novgorod Barge #2t|Novgorod Barge #3|Novgorod Barge #4
  SetName = Novgorod Ferry
  Apply

SelectRegion = $Petrozavodsk

SelectFaction = $RED
SelectRegion = $Petrozavodsk
  CreateGroup
  Posture = $Defensive
  SetKind = $Nav
  Entranch = 0
  SetName = Petrozavodsk Ferry
  Apply
  CreateUnit
  SetType = $uni_RED_RT2
  SUFlavorName = Petrozavodsk Barge #1|Petrozavodsk Barge #2t|Petrozavodsk Barge #3|Petrozavodsk Barge #4
  SetName = Petrozavodsk Ferry
  Apply
